metadata:
  appname: backend-api
  namespace: dev
replicasCount: 2
port: 3005
hostAliases:
  - ip: "1.1.1.1"
    hostnames:
      - "mongodb01"
  - ip: "2.2.2.2"
    hostnames:
      - "mongodb-2"
  - ip: "3.3.3.3"
    hostnames:
      - "mongodb-3"
image:
  registry: https://gchr.io
  repo: dev
  name: backend-api
  tag: 1.0.4
  imagePullSecrets: ghcr-dev-secret
service:
  - name: 
    port: 
    targetPort: 
    protocol: TCP
env:
  configs:
    PORT: 3005
    key1: value1
    key2: value2
  secrets:
    key1: value1
    key2: value2
secretsType: Opaque