apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.metadata.appname }}-envs
  namespace: {{ .Values.metadata.namespace }}
type: {{ .Values.secretsType }}
data:
  {{- range $key, $val := .Values.env.secrets }}
    {{ $key }}: {{   print $val | b64enc }}
  {{- end}}