apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.metadata.appname }}
  namespace: {{ .Values.metadata.namespace }}
  labels:
    app: {{ .Values.metadata.appname }}
spec:
  type: ClusterIP
  ports:
{{- range $name, $port, $targetPort := .Values.service }}
  - name: {{ $name | quote }}
    port: {{ $port }}
    targetPort: {{ $targetPort }}
    protocol: {{ $targetPort }}
{{- end}}
  selector:
    app: {{ .Values.metadata.appname }}
